### ISSUE TITLE
moraba font

### ISSUE THREAD

**Issue by MobinAssari** [mahdyar/persian-fonts-flutter#10]

**Comment by mahdyar** [comment]
سلام @MobinAssari؛
من مطمئن نیستم منظورتون از باز کردن این ایشو چی هست، ولی احتمالاً می‌خواید که فونت «مربع» رو به پکیج اضافه کنم، در اون حالت متاسفانه باید بگم این کار امکان پذیر نیست چون این فونت، یک فونت رایگان و آزاد نیست و لایسنس داره.
