### ISSUE TITLE
No named parameter with the name 'headline2'.

### ISSUE THREAD

**Issue by MobinAssari** [mahdyar/persian-fonts-flutter#11]
hey
when i build my project i get these errors

[+2388 ms] [+3427 ms] /C:/Users/mobin/AppData/Local/Pub/Cache/hosted/pub.dev/persian_fonts-1.0.5/lib/persian_fonts.dart:13:5: Error: No named parameter with the name 'headline2'.
[        ] [   +1 ms]     headline2: PersianFonts.Vazir,
[        ] [        ]     ^^^^^^^^^
[        ] [        ] /D:/src/flutter_windows_3.16.3-stable/flutter/packages/flutter/lib/src/material/text_theme.dart:89:9: Context: Found this candidate, but the arguments don't match.
[        ] [        ]   const TextTheme({
[        ] [        ]         ^^^^^^^^^
[        ] [        ] /C:/Users/mobin/AppData/Local/Pub/Cache/hosted/pub.dev/persian_fonts-1.0.5/lib/persian_fonts.dart:35:5: Error: No named parameter with the name 'headline2'.
[        ] [        ]     headline2: PersianFonts.Samim,
[        ] [        ]     ^^^^^^^^^
[        ] [        ] /D:/src/flutter_windows_3.16.3-stable/flutter/packages/flutter/lib/src/material/text_theme.dart:89:9: Context: Found this candidate, but the arguments don't match.
[        ] [        ]   const TextTheme({
[        ] [        ]         ^^^^^^^^^
[        ] [        ] /C:/Users/mobin/AppData/Local/Pub/Cache/hosted/pub.dev/persian_fonts-1.0.5/lib/persian_fonts.dart:58:5: Error: No named parameter with the name 'headline2'.
[        ] [        ]     headline2: PersianFonts.Shabnam,
[        ] [        ]     ^^^^^^^^^
[        ] [        ] /D:/src/flutter_windows_3.16.3-stable/flutter/packages/flutter/lib/src/material/text_theme.dart:89:9: Context: Found this candidate, but the arguments don't match.
[        ] [        ]   const TextTheme({
[        ] [        ]         ^^^^^^^^^
[        ] [        ] /C:/Users/mobin/AppData/Local/Pub/Cache/hosted/pub.dev/persian_fonts-1.0.5/lib/persian_fonts.dart:80:5: Error: No named parameter with the name 'headline2'.
[        ] [        ]     headline2: PersianFonts.Sahel,
[        ] [        ]     ^^^^^^^^^
[        ] [        ] /D:/src/flutter_windows_3.16.3-stable/flutter/packages/flutter/lib/src/material/text_theme.dart:89:9: Context: Found this candidate, but the arguments don't match.
[        ] [        ]   const TextTheme({
[        ] [        ]         ^^^^^^^^^
[        ] [        ] /C:/Users/mobin/AppData/Local/Pub/Cache/hosted/pub.dev/persian_fonts-1.0.5/lib/persian_fonts.dart:102:5: Error: No named parameter with the name 'headline2'.
[        ] [        ]     headline2: PersianFonts.Yekan,
[        ] [        ]     ^^^^^^^^^

**Comment by mahdyar** [comment]
Hi, really sorry for the delay, but finally fixed in #12 :)
